# import os
# from os.path import join
#
# # Globals ---------------------------------------------------------------------
# configfile: "config.json"
#
# # define parameters
# num_threads = config["NUM_THREADS"]
#
# # define path
# in_data_path = join(config["ROOT_PATH"], "in")
# in_data = os.listdir(in_data_path)
# out_data_path = join(config["ROOT_PATH"], "out")
# # define result path
# log_path = join(out_data_path, "log")
# fastqc_path = join(out_data_path, "fastqc")

# Rules -----------------------------------------------------------------------

rule fastqc:
    input:
        "data/in/test1.fastq"
    output:
        "data/out/"
    shell:
        'fastqc -o {output} {input}'


# rule all:
#
#
# rule clean:
#     shell:
#         """
#         rm -rf {out_data_path} && mkdir {out_data_path}
#         mkdir {log_path}
#         mkdir {fastqc_path}
#         """
#
# rule fastqc:
#     input:
#         {dataset}
#     output:
#         fastqc_path
#     threads: num_threads
#     log: '{log_path}/log.fastqc'
#     shell:
#         'fastqc -o {output} {input}'
